# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5d59ae1d9ca8975c0edf34d27d3af54f1aad9f78b1f7d9aa6f4adf73b3243a75bfbf01f508a460617a2907458f5cbde4f38e64125868bdacf54a0985ee9f75d

test:
  secret_key_base: 215fbe997f8aa5ac2cb977f81cd06f57dc3da03c19025c9c4ede1db9d6a9b49e1c0a891ce836b1068d422118fe3a8cd61c81acef88966527eb3dec649287b5a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
